/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_linc_ndklibrary_SecondLib */

#ifndef _Included_com_linc_ndklibrary_SecondLib
#define _Included_com_linc_ndklibrary_SecondLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_linc_ndklibrary_SecondLib
 * Method:    intMethod
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_linc_ndklibrary_SecondLib_intMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_linc_ndklibrary_SecondLib
 * Method:    stringMethod
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_linc_ndklibrary_SecondLib_stringMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
